### ISSUE TITLE
Dynamo Process checker 

### ISSUE THREAD

**Issue by brencass** [johnpierson/FETCH#1]
@johnpierson Probably worth adding a process checker to check if Dynamo is within memory. If dynamo is within memory it will probably error out when either deleting or add new packages. 

EG. Dynamo could be loaded within another revit instance or even previously been loaded within that instance, and therefore will error out this addon because it cannot delete or install the new packages.

Run this method to apply a value within the globals parameter, then if the parameter is true it wont download packages but if false it will. Or modify this method to output a bool as part of a check.

![image](https://user-images.githubusercontent.com/14090637/192232632-be7a42c8-9984-4163-afb0-ad412574991f.png)

You will need to add "using System.Diagnostics;" at the top of your code, and add a new Globals called IsDynamoInMemory.

        /// <summary>
        /// Gets all processes running on the machine then checks if they are "Revit" based. Then if it does find any it checks if Dynamo dll's are in memory.
        /// If yes it changes Global "IsDynamoInMemory" to True
        /// </summary>
                public static void CheckIfProcessContainDynamo()
        {
            List<bool> tempBoolList = new List<bool>();

            foreach (Process process in Process.GetProcessesByName("revit"))
            {
                foreach (ProcessModule module in process.Modules)
                {
                    if (module.FileName.ToLower().Contains("dynamo"))
                    {
                        tempBoolList.Add(true);
                    }
                }
            }
            if (tempBoolList.Count() > 0)
            {
                Globals.IsDynamoInMemory = true;
            }
            else
            {
                Globals.IsDynamoInMemory = false;
            }
        }
        
        
Edit: I have changed "Process.GetProcesses()" to "Process.GetProcessesByName("revit")" and got rid of the IF statement from the attached code but is still showing in the image.

**Comment by johnpierson** [comment]
Ah that makes sense. Will end up adding that soon. One thing is, I would want to ensure that the Revit version matches the one I am checking it from. In the case of someone running 2022 and 2023

**Comment by brencass** [comment]
After the "foreach (Process process in Process.GetProcessesByName("revit"))" for the process and before it checks the modules you can add the below. 

Then use this FilePath to see if it contains the VersionNumber from revit, if yes then it checks if Dynamo is running. 

string fullPath = process.MainModule.FileName;

What is outputted from ProcessName(does not include Autodesk Revit 20XX) and the mainmodule FileName(includes version from file path):
![image](https://user-images.githubusercontent.com/14090637/194049868-c495d037-6c9f-450a-b534-62ae802210f1.png)

Code used for the above window popup:
![image](https://user-images.githubusercontent.com/14090637/194050753-c259a417-14de-44af-99b2-edaf2a4578a9.png)

**Comment by johnpierson** [comment]
That makes sense to me! I could see this happening with multiple revit
sessions open for sure. Will get that added!
