### ISSUE TITLE
Installer flagged as trojan

### ISSUE THREAD

**Issue by NicoBrown** [johnpierson/FETCH#2]
Hi John,

Thanks for all of the hard work in the dynamo community, I downloaded the installer.exe but when I went to install it Microsoft flagged it as a trojan virus and wouldn't let me, just so you know.

Also have you done any demos or blog posts about this Add-in yet?

**Comment by johnpierson** [comment]
Hey @NicoBrown ! I have not had a chance to publicize it yet. 

And yes, unfortunately, I have also not signed the installer fully and windows tends to be a bit more strict than Revit with signed code, so I am not too sure what to do about that in the immediate future.

The code is all OpenSource and there isn't a virus, so yeah. lol
