### ISSUE TITLE
Fetch not working for 2021 and 2022

### ISSUE THREAD

**Issue by NomadicNiche** [johnpierson/FETCH#4]
Hello John,

First off, thank you for all your contributions to the Dynamo community!

I am testing out Fetch and it seems to only install on 2023. It has been working great with 2023 so far by the way.

I looked at the Addins folder in ProgramData for Revit 2021 and 2022 and there was not a folder for Fetch. I tried copying the Fetch folder from 2023 and pasted them to 2021 and 2022, but no change.

**Comment by johnpierson** [comment]
fetch only works in 2023 for now. Will need to add support for other versions
